plugins {
    id 'java'
    id 'application'
}

group = 'com.shojo'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25) // usa JDK 17 o 21 LTS
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
}

application {
    // esto debe coincidir con el package real de Main.java (ver paso 3)
    mainClass = 'party.view.Main'
}

tasks.test {
    useJUnitPlatform()
}

